# Usar Node.js como imagen base
FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente al contenedor
COPY . .

# Exponer el puerto en el que corre la API
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "run", "start"]