version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: transactions_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "1"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network

  antifraude-service:
    build: ./antifraude-service
    container_name: antifraude-service
    depends_on:
      - kafka
    environment:
      DATABASE_HOST: transactions_db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: transactions
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLIENT_ID: antifraude-service
      KAFKA_GROUP_ID: antifraude-consumer
      KAFKA_TOPIC: transactions
    networks:
      - app-network

  api-transacciones:
    build: ./api-transacciones
    container_name: api-transacciones
    depends_on:
      - kafka
      - postgres
    environment:
      DATABASE_HOST: transactions_db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: transactions
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLIENT_ID: api-transacciones-client
      KAFKA_GROUP_ID: transactions-consumer
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge